server:
  port: 8080  # Port for the API Gateway

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay
        - id: room-service
          uri: http://room-service:8082
          predicates:
            - Path=/rooms/**
          filters:
            - TokenRelay
        - id: event-service
          uri: http://event-service:8083
          predicates:
            - Path=/events/**
          filters:
            - TokenRelay
        - id: booking-service
          uri: http://booking-service:8084
          predicates:
            - Path=/bookings/**
          filters:
            - TokenRelay
        - id: approval-service
          uri: http://approval-service:8085
          predicates:
            - Path=/approvals/**
          filters:
            - TokenRelay

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master

# Kafka configuration
spring:
  kafka:
    bootstrap-servers: kafka-broker:9092
    consumer:
      group-id: api-gateway-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

# Schema Registry
schema-registry:
  url: http://schema-registry:8081
